version: '3.9'
services:
  postgres:
    image: postgres:16.2
    restart: always
    environment:
      - POSTGRES_DB=integration_platform
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: '3'
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: 'pg_isready --username=postgres && psql --username=postgres --list'
      timeout: 10s
      retries: 20
  integration_platform:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '5000:5000'
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=integration_platform;User Id=postgres;Password=postgres
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      postgres:
        condition: service_healthy
  consumer:
    build:
      context: .
      dockerfile: Consumer/Dockerfile
    restart: always
    ports:
      - '5001:5001'
    environment:
      - IntegrationPlatform__BaseUrl=http://integration_platform:5000/api/
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      postgres:
        condition: service_healthy
      integration_platform:
        condition: service_started